# Generated by Django 6.0.3 on 2026-03-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safetyevent",
            name="danger",
        ),
        migrations.RemoveField(
            model_name="safetyevent",
            name="email_sent",
        ),
        migrations.RemoveField(
            model_name="safetyevent",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="safetyevent",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="safetyevent",
            name="person_detected",
        ),
        migrations.AddField(
            model_name="safetyevent",
            name="area_type",
            field=models.CharField(
                blank=True,
                choices=[("area1", "Area 1"), ("area2", "Area 2"), ("area3", "Area 3")],
                max_length=20,
                null=True,
            ),
        ),
    ]
